[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "next dev"
  targetPort = 3000

[[plugins]]
  package = "@netlify/next"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self'"

[functions]
  node_bundler = "esbuild"
