// // // src/app/layout.tsx
// // // import { Footer } from "@/components/Footer";
// // // import NavbarTail from "@/components/navbar/Navbar";
// // // import "@/styles/globals.css";
// // // import { ReactNode } from "react";

// // // export const metadata = {
// // //   title: "ZionCWB",
// // //   description: "Portfólio pessoal André Lopes Paiva",
// // // };

// // // export default function RootLayout({ children }: { children: ReactNode }) {
// // //   return (
// // //     <html lang="pt-br">
// // //       <body className="bg-gradient-to-br from-slate-950 to-emerald-950 text-green-500 font-futuristic min-h-screen flex flex-col">
// // //         <header className="w-full">
// // //           <NavbarTail />
// // //         </header>
// // //         <main className="flex-grow flex justify-center justify-items-center items-center">
// // //           {children}
// // //         </main>
// // //         <Footer />       
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // 'use client';
// // /** @jsxImportSource @emotion/react */
// // import { ChakraProvider, CSSReset, ColorModeScript, extendTheme } from "@chakra-ui/react"
// // import { Global, css } from "@emotion/react"
// // import type { AppProps } from "next/app"
// // import Head from "next/head"
// // import { Roboto_Mono } from "next/font/google"
// // import { Noto_Sans } from "next/font/google"

// // const robotoMono = Roboto_Mono({
// //   weight: ["400", "700"],
// //   subsets: ["latin"],
// //   display: "swap",
// // })

// // const notoSans = Noto_Sans({
// //   weight: ["400", "700"],
// //   subsets: ["latin"],
// //   display: "swap",
// // })

// // const customTheme = extendTheme({
// //   fonts: {
// //     heading: notoSans.style.fontFamily,
// //     body: notoSans.style.fontFamily,
// //     mono: robotoMono.style.fontFamily,
// //   },
// // })

// // export default function App({ Component, pageProps }: AppProps) {
// //   return (
// //     <>
// //       <Head>
// //         <title>Create Next App</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
// //       <Global
// //         styles={css`
// //           body {
// //             margin: 0;
// //           }
// //         `}
// //       />
// //       <ChakraProvider theme={customTheme}>
// //         <CSSReset />
// //         <ColorModeScript initialColorMode="dark" />
// //         <body className="bg-gradient-to-br from-slate-900 to-emerald-900 text-green-400 font-futuristic min-h-screen flex flex-col">
// //           <Component {...pageProps} />
// //         </body>
// //       </ChakraProvider>
// //     </>
// //   )
// // }

// import { Roboto_Mono, Noto_Sans } from "next/font/google"
// import Footer from "@/components/Footer"
// import NavbarTail from "@/components/navbar/Navbar"
// import "@/styles/globals.css"
// import type { ReactNode } from "react"

// const robotoMono = Roboto_Mono({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   display: "swap",
// })

// const notoSans = Noto_Sans({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   display: "swap",
// })

// export const metadata = {
//   title: "ZionCWB",
//   description: "Portfólio pessoal André Lopes Paiva",
// }

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="pt-br" className={`${notoSans.className}`}>
//       <body className="bg-gradient-to-br from-slate-950 to-emerald-950 text-green-500 min-h-screen flex flex-col">
//         <header className="w-full">
//           <NavbarTail isScrolled={false} />
//         </header>
//         <main className="flex-grow flex justify-center justify-items-center items-center">{children}</main>
//         <Footer />
//         <style jsx global>{`
//           :root {
//             --font-mono: ${robotoMono.style.fontFamily};
//           }
//         `}</style>
//       </body>
//     </html>
//   )
// }

import { Roboto_Mono, Noto_Sans } from "next/font/google";
import  Footer  from "@/components/Footer";
import "@/styles/globals.css";
import type { ReactNode } from "react";
import Navbar from "@/components/navbar/Navbar";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
})

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "ZionCWB",
  description: "Portfólio pessoal André Lopes Paiva",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br" className={`${notoSans.className} ${robotoMono.variable}`}>
      <body className="bg-gradient-to-br from-slate-950 to-emerald-950 text-green-500 min-h-screen flex flex-col">
        <header className="w-full">
          <Navbar isScrolled={false} />
        </header>
        <main className="flex-grow flex justify-center justify-items-center items-center">{children}</main>
        <Footer />
      </body>
    </html>
  )
}

